quickbar_toggle:
  name: Toggle QuickBar
  description: Open/close a QuickBar by alias (acts as a toggle on the Android app).
  fields:
    alias:
      name: Alias
      description: QuickBar alias defined in the Android TV app.
      example: living_room
      required: true
      selector:
        text:

camera_toggle:
  name: Toggle Camera PiP
  description: Show/hide a camera PiP by alias (toggle handled by the Android app).
  fields:
    camera_alias:
      name: Camera Alias
      description: Camera alias defined in the Android TV app.
      example: porch_cam
      required: true
      selector:
        text:


notify:
  name: Send a Notification using QuickBars
  description: Show a rich notification on the TV with optional actions.
  fields:
    device_id:
      name: Target QuickBars device
      required: false
      description: >
        Select a specific QuickBars device. If omitted, the notification is sent
        to all connected QuickBars devices (default).
      selector:
        device:
          integration: quickbars

    title:
      name: Title
      description: Title of the notification.
      required: false
      selector:
        text:

    mdi_icon:
      name: Icon
      description: Pick an MDI icon (e.g., mdi:bell). The integration will embed the SVG and show it near the title.
      required: false
      selector:
        icon:
          placeholder: mdi:bell

    message:
      name: Message
      description: Main message text.
      required: true
      selector:
        text:
      example: 'Door opened at {{ now().strftime("%H:%M:%S") }}'

    actions:
      name: Actions
      description: List of {id, label} objects.
      required: false
      example:
        - id: "open_door"
          label: "Open"
        - id: "dismiss"
          label: "Dismiss"
      selector:
        object:

    position:
      name: Position
      required: true
      default: bottom_left
      selector:
        select:
          options:
            - label: Top left
              value: top_left
            - label: Top right
              value: top_right
            - label: Bottom left
              value: bottom_left
            - label: Bottom right
              value: bottom_right

    length:
      name: Length
      description: How long to show the notification (seconds).
      required: false
      default: 6
      selector:
        number:
          min: 3
          max: 120
          step: 1
          mode: slider
          unit_of_measurement: s

    color:
      name: Overlay color
      description: RGB color; transparency is set separately.
      required: false
      default: "#8cd0e6"
      selector:
        color_rgb:

    transparency:
      name: Transparency
      description: 0.0 = opaque, 1.0 = fully transparent
      required: false
      default: 0.0
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
          mode: slider

    interrupt:
      name: Interrupt
      description: Hide any existing notification, and show this one immediately.
      required: false
      default: false
      selector:
        boolean:

    image:
      name: Image source
      description: |
        Provide ONE of:
          - url: "https://example.com/pic.jpg"
          - path: "folder/file.jpg"      (relative to /config/www → served at /local/folder/file.jpg)
          - media_id: "media-source://media_source/local/folder/file.jpg"  (from My media)
      required: false
      selector:
        object:
      example: >
        {"url": "https://example.com/pic.jpg"} or
        {"path": "images/quickbars-hero.png"} or
        {"media_id": "media-source://media_source/local/images/quickbars-hero.png"}

    sound:
      name: Sound
      description: |
        Provide ONE of:
          - url: "https://example.com/file.mp3"
          - path: "chimes/ding.mp3"      (relative to /config/www → /local/chimes/ding.mp3)
          - media_id: "media-source://media_source/local/chimes/ding.mp3"  (from My media)
      required: false
      selector:
        object:
      example: >
        {"url": "https://example.com/file.mp3"} or
        {"path": "chimes/ding.mp3"} or
        {"media_id": "media-source://media_source/local/chimes/ding.mp3"}
      

    sound_volume_percent:
      name: Sound volume (%)
      description: >
        0–200%. 100% = system volume; >100% uses post-mix boost (may clip/distort).
      required: false
      default: 100
      selector:
        number:
          min: 0
          max: 200
          step: 5
          unit_of_measurement: "%"
          mode: slider
